//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-sources.jar!org/apache/commons/lang3/builder/IDKey.java
//

#include "J2ObjC_source.h"
#include "java/lang/System.h"
#include "org/apache/commons/lang3/builder/IDKey.h"

@interface OrgApacheCommonsLang3BuilderIDKey () {
 @public
  id value_;
  jint id__;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheCommonsLang3BuilderIDKey, value_, id)

@implementation OrgApacheCommonsLang3BuilderIDKey

- (instancetype)initWithId:(id)_value {
  OrgApacheCommonsLang3BuilderIDKey_initWithId_(self, _value);
  return self;
}

- (NSUInteger)hash {
  return id__;
}

- (jboolean)isEqual:(id)other {
  if (!([other isKindOfClass:[OrgApacheCommonsLang3BuilderIDKey class]])) {
    return false;
  }
  OrgApacheCommonsLang3BuilderIDKey *idKey = (OrgApacheCommonsLang3BuilderIDKey *) cast_chk(other, [OrgApacheCommonsLang3BuilderIDKey class]);
  if (id__ != ((OrgApacheCommonsLang3BuilderIDKey *) nil_chk(idKey))->id__) {
    return false;
  }
  return value_ == idKey->value_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 2, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithId:);
  methods[1].selector = @selector(hash);
  methods[2].selector = @selector(isEqual:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "LNSObject;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "id__", "I", .constantValue.asLong = 0, 0x12, 3, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSObject;", "hashCode", "equals", "id" };
  static const J2ObjcClassInfo _OrgApacheCommonsLang3BuilderIDKey = { "IDKey", "org.apache.commons.lang3.builder", ptrTable, methods, fields, 7, 0x10, 3, 2, -1, -1, -1, -1, -1 };
  return &_OrgApacheCommonsLang3BuilderIDKey;
}

@end

void OrgApacheCommonsLang3BuilderIDKey_initWithId_(OrgApacheCommonsLang3BuilderIDKey *self, id _value) {
  NSObject_init(self);
  self->id__ = JavaLangSystem_identityHashCodeWithId_(_value);
  self->value_ = _value;
}

OrgApacheCommonsLang3BuilderIDKey *new_OrgApacheCommonsLang3BuilderIDKey_initWithId_(id _value) {
  J2OBJC_NEW_IMPL(OrgApacheCommonsLang3BuilderIDKey, initWithId_, _value)
}

OrgApacheCommonsLang3BuilderIDKey *create_OrgApacheCommonsLang3BuilderIDKey_initWithId_(id _value) {
  J2OBJC_CREATE_IMPL(OrgApacheCommonsLang3BuilderIDKey, initWithId_, _value)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheCommonsLang3BuilderIDKey)
