//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-fis-sources.jar!org/apache/commons/lang3/builder/RecursiveToStringStyle.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/StringBuffer.h"
#include "java/util/Collection.h"
#include "org/apache/commons/lang3/ClassUtils.h"
#include "org/apache/commons/lang3/builder/RecursiveToStringStyle.h"
#include "org/apache/commons/lang3/builder/ReflectionToStringBuilder.h"
#include "org/apache/commons/lang3/builder/ToStringStyle.h"

inline jlong OrgApacheCommonsLang3BuilderRecursiveToStringStyle_get_serialVersionUID(void);
#define OrgApacheCommonsLang3BuilderRecursiveToStringStyle_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheCommonsLang3BuilderRecursiveToStringStyle, serialVersionUID, jlong)

@implementation OrgApacheCommonsLang3BuilderRecursiveToStringStyle

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheCommonsLang3BuilderRecursiveToStringStyle_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)appendDetailWithJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
                                withNSString:(NSString *)fieldName
                                      withId:(id)value {
  if (!OrgApacheCommonsLang3ClassUtils_isPrimitiveWrapperWithIOSClass_([nil_chk(value) java_getClass]) && ![NSString_class_() isEqual:[value java_getClass]] && [self acceptWithIOSClass:[value java_getClass]]) {
    (void) [((JavaLangStringBuffer *) nil_chk(buffer)) appendWithNSString:OrgApacheCommonsLang3BuilderReflectionToStringBuilder_toStringWithId_withOrgApacheCommonsLang3BuilderToStringStyle_(value, self)];
  }
  else {
    [super appendDetailWithJavaLangStringBuffer:buffer withNSString:fieldName withId:value];
  }
}

- (void)appendDetailWithJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
                                withNSString:(NSString *)fieldName
                      withJavaUtilCollection:(id<JavaUtilCollection>)coll {
  [self appendClassNameWithJavaLangStringBuffer:buffer withId:coll];
  [self appendIdentityHashCodeWithJavaLangStringBuffer:buffer withId:coll];
  [self appendDetailWithJavaLangStringBuffer:buffer withNSString:fieldName withNSObjectArray:[((id<JavaUtilCollection>) nil_chk(coll)) toArray]];
}

- (jboolean)acceptWithIOSClass:(IOSClass *)clazz {
  return true;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 0, 2, -1, 3, -1, -1 },
    { NULL, "Z", 0x4, 4, 5, -1, 6, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(appendDetailWithJavaLangStringBuffer:withNSString:withId:);
  methods[2].selector = @selector(appendDetailWithJavaLangStringBuffer:withNSString:withJavaUtilCollection:);
  methods[3].selector = @selector(acceptWithIOSClass:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgApacheCommonsLang3BuilderRecursiveToStringStyle_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "appendDetail", "LJavaLangStringBuffer;LNSString;LNSObject;", "LJavaLangStringBuffer;LNSString;LJavaUtilCollection;", "(Ljava/lang/StringBuffer;Ljava/lang/String;Ljava/util/Collection<*>;)V", "accept", "LIOSClass;", "(Ljava/lang/Class<*>;)Z" };
  static const J2ObjcClassInfo _OrgApacheCommonsLang3BuilderRecursiveToStringStyle = { "RecursiveToStringStyle", "org.apache.commons.lang3.builder", ptrTable, methods, fields, 7, 0x1, 4, 1, -1, -1, -1, -1, -1 };
  return &_OrgApacheCommonsLang3BuilderRecursiveToStringStyle;
}

@end

void OrgApacheCommonsLang3BuilderRecursiveToStringStyle_init(OrgApacheCommonsLang3BuilderRecursiveToStringStyle *self) {
  OrgApacheCommonsLang3BuilderToStringStyle_init(self);
}

OrgApacheCommonsLang3BuilderRecursiveToStringStyle *new_OrgApacheCommonsLang3BuilderRecursiveToStringStyle_init() {
  J2OBJC_NEW_IMPL(OrgApacheCommonsLang3BuilderRecursiveToStringStyle, init)
}

OrgApacheCommonsLang3BuilderRecursiveToStringStyle *create_OrgApacheCommonsLang3BuilderRecursiveToStringStyle_init() {
  J2OBJC_CREATE_IMPL(OrgApacheCommonsLang3BuilderRecursiveToStringStyle, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheCommonsLang3BuilderRecursiveToStringStyle)
