//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-sources.jar!org/apache/commons/lang3/text/FormatFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsLang3TextFormatFactory")
#ifdef RESTRICT_OrgApacheCommonsLang3TextFormatFactory
#define INCLUDE_ALL_OrgApacheCommonsLang3TextFormatFactory 0
#else
#define INCLUDE_ALL_OrgApacheCommonsLang3TextFormatFactory 1
#endif
#undef RESTRICT_OrgApacheCommonsLang3TextFormatFactory

#if !defined (OrgApacheCommonsLang3TextFormatFactory_) && (INCLUDE_ALL_OrgApacheCommonsLang3TextFormatFactory || defined(INCLUDE_OrgApacheCommonsLang3TextFormatFactory))
#define OrgApacheCommonsLang3TextFormatFactory_

@class JavaTextFormat;
@class JavaUtilLocale;

@protocol OrgApacheCommonsLang3TextFormatFactory < JavaObject >

- (JavaTextFormat *)getFormatWithNSString:(NSString *)name
                             withNSString:(NSString *)arguments
                       withJavaUtilLocale:(JavaUtilLocale *)locale;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsLang3TextFormatFactory)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsLang3TextFormatFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsLang3TextFormatFactory")
