//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-fis-sources.jar!org/apache/commons/lang3/text/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsLang3TextPackage_info")
#ifdef RESTRICT_OrgApacheCommonsLang3TextPackage_info
#define INCLUDE_ALL_OrgApacheCommonsLang3TextPackage_info 0
#else
#define INCLUDE_ALL_OrgApacheCommonsLang3TextPackage_info 1
#endif
#undef RESTRICT_OrgApacheCommonsLang3TextPackage_info

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsLang3TextPackage_info")
