//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-fis-sources.jar!org/apache/commons/lang3/event/package-info.java
//

#include "J2ObjC_source.h"
#include "org/apache/commons/lang3/event/package-info.h"
