//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-codec-1.10-sources.jar!org/apache/commons/codec/Encoder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsCodecEncoder")
#ifdef RESTRICT_OrgApacheCommonsCodecEncoder
#define INCLUDE_ALL_OrgApacheCommonsCodecEncoder 0
#else
#define INCLUDE_ALL_OrgApacheCommonsCodecEncoder 1
#endif
#undef RESTRICT_OrgApacheCommonsCodecEncoder

#if !defined (OrgApacheCommonsCodecEncoder_) && (INCLUDE_ALL_OrgApacheCommonsCodecEncoder || defined(INCLUDE_OrgApacheCommonsCodecEncoder))
#define OrgApacheCommonsCodecEncoder_

@protocol OrgApacheCommonsCodecEncoder < JavaObject >

- (id)encodeWithId:(id)source;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCodecEncoder)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCodecEncoder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsCodecEncoder")
