//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-codec-1.10-sources.jar!org/apache/commons/codec/BinaryEncoder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsCodecBinaryEncoder")
#ifdef RESTRICT_OrgApacheCommonsCodecBinaryEncoder
#define INCLUDE_ALL_OrgApacheCommonsCodecBinaryEncoder 0
#else
#define INCLUDE_ALL_OrgApacheCommonsCodecBinaryEncoder 1
#endif
#undef RESTRICT_OrgApacheCommonsCodecBinaryEncoder

#if !defined (OrgApacheCommonsCodecBinaryEncoder_) && (INCLUDE_ALL_OrgApacheCommonsCodecBinaryEncoder || defined(INCLUDE_OrgApacheCommonsCodecBinaryEncoder))
#define OrgApacheCommonsCodecBinaryEncoder_

#define RESTRICT_OrgApacheCommonsCodecEncoder 1
#define INCLUDE_OrgApacheCommonsCodecEncoder 1
#include "org/apache/commons/codec/Encoder.h"

@class IOSByteArray;

@protocol OrgApacheCommonsCodecBinaryEncoder < OrgApacheCommonsCodecEncoder, JavaObject >

- (IOSByteArray *)encodeWithByteArray:(IOSByteArray *)source;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCodecBinaryEncoder)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCodecBinaryEncoder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsCodecBinaryEncoder")
