//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-sources.jar!org/apache/commons/lang3/reflect/InheritanceUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsLang3ReflectInheritanceUtils")
#ifdef RESTRICT_OrgApacheCommonsLang3ReflectInheritanceUtils
#define INCLUDE_ALL_OrgApacheCommonsLang3ReflectInheritanceUtils 0
#else
#define INCLUDE_ALL_OrgApacheCommonsLang3ReflectInheritanceUtils 1
#endif
#undef RESTRICT_OrgApacheCommonsLang3ReflectInheritanceUtils

#if !defined (OrgApacheCommonsLang3ReflectInheritanceUtils_) && (INCLUDE_ALL_OrgApacheCommonsLang3ReflectInheritanceUtils || defined(INCLUDE_OrgApacheCommonsLang3ReflectInheritanceUtils))
#define OrgApacheCommonsLang3ReflectInheritanceUtils_

@class IOSClass;

@interface OrgApacheCommonsLang3ReflectInheritanceUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)distanceWithIOSClass:(IOSClass *)child
                withIOSClass:(IOSClass *)parent;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsLang3ReflectInheritanceUtils)

FOUNDATION_EXPORT void OrgApacheCommonsLang3ReflectInheritanceUtils_init(OrgApacheCommonsLang3ReflectInheritanceUtils *self);

FOUNDATION_EXPORT OrgApacheCommonsLang3ReflectInheritanceUtils *new_OrgApacheCommonsLang3ReflectInheritanceUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheCommonsLang3ReflectInheritanceUtils *create_OrgApacheCommonsLang3ReflectInheritanceUtils_init();

FOUNDATION_EXPORT jint OrgApacheCommonsLang3ReflectInheritanceUtils_distanceWithIOSClass_withIOSClass_(IOSClass *child, IOSClass *parent);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsLang3ReflectInheritanceUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsLang3ReflectInheritanceUtils")
