//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-codec-1.10-sources.jar!org/apache/commons/codec/digest/Crypt.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsCodecDigestCrypt")
#ifdef RESTRICT_OrgApacheCommonsCodecDigestCrypt
#define INCLUDE_ALL_OrgApacheCommonsCodecDigestCrypt 0
#else
#define INCLUDE_ALL_OrgApacheCommonsCodecDigestCrypt 1
#endif
#undef RESTRICT_OrgApacheCommonsCodecDigestCrypt

#if !defined (OrgApacheCommonsCodecDigestCrypt_) && (INCLUDE_ALL_OrgApacheCommonsCodecDigestCrypt || defined(INCLUDE_OrgApacheCommonsCodecDigestCrypt))
#define OrgApacheCommonsCodecDigestCrypt_

@class IOSByteArray;

@interface OrgApacheCommonsCodecDigestCrypt : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)cryptWithByteArray:(IOSByteArray *)keyBytes;

+ (NSString *)cryptWithByteArray:(IOSByteArray *)keyBytes
                    withNSString:(NSString *)salt;

+ (NSString *)cryptWithNSString:(NSString *)key;

+ (NSString *)cryptWithNSString:(NSString *)key
                   withNSString:(NSString *)salt;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCodecDigestCrypt)

FOUNDATION_EXPORT void OrgApacheCommonsCodecDigestCrypt_init(OrgApacheCommonsCodecDigestCrypt *self);

FOUNDATION_EXPORT OrgApacheCommonsCodecDigestCrypt *new_OrgApacheCommonsCodecDigestCrypt_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheCommonsCodecDigestCrypt *create_OrgApacheCommonsCodecDigestCrypt_init();

FOUNDATION_EXPORT NSString *OrgApacheCommonsCodecDigestCrypt_cryptWithByteArray_(IOSByteArray *keyBytes);

FOUNDATION_EXPORT NSString *OrgApacheCommonsCodecDigestCrypt_cryptWithByteArray_withNSString_(IOSByteArray *keyBytes, NSString *salt);

FOUNDATION_EXPORT NSString *OrgApacheCommonsCodecDigestCrypt_cryptWithNSString_(NSString *key);

FOUNDATION_EXPORT NSString *OrgApacheCommonsCodecDigestCrypt_cryptWithNSString_withNSString_(NSString *key, NSString *salt);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCodecDigestCrypt)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsCodecDigestCrypt")
