//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-lang3-3.4-sources.jar!org/apache/commons/lang3/EnumUtils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsLang3EnumUtils")
#ifdef RESTRICT_OrgApacheCommonsLang3EnumUtils
#define INCLUDE_ALL_OrgApacheCommonsLang3EnumUtils 0
#else
#define INCLUDE_ALL_OrgApacheCommonsLang3EnumUtils 1
#endif
#undef RESTRICT_OrgApacheCommonsLang3EnumUtils

#if !defined (OrgApacheCommonsLang3EnumUtils_) && (INCLUDE_ALL_OrgApacheCommonsLang3EnumUtils || defined(INCLUDE_OrgApacheCommonsLang3EnumUtils))
#define OrgApacheCommonsLang3EnumUtils_

@class IOSClass;
@class IOSLongArray;
@class IOSObjectArray;
@class JavaLangEnum;
@class JavaUtilEnumSet;
@protocol JavaLangIterable;
@protocol JavaUtilList;
@protocol JavaUtilMap;

@interface OrgApacheCommonsLang3EnumUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (jlong)generateBitVectorWithIOSClass:(IOSClass *)enumClass
                 withJavaLangEnumArray:(IOSObjectArray *)values;

+ (jlong)generateBitVectorWithIOSClass:(IOSClass *)enumClass
                  withJavaLangIterable:(id<JavaLangIterable>)values;

+ (IOSLongArray *)generateBitVectorsWithIOSClass:(IOSClass *)enumClass
                           withJavaLangEnumArray:(IOSObjectArray *)values;

+ (IOSLongArray *)generateBitVectorsWithIOSClass:(IOSClass *)enumClass
                            withJavaLangIterable:(id<JavaLangIterable>)values;

+ (JavaLangEnum *)getEnumWithIOSClass:(IOSClass *)enumClass
                         withNSString:(NSString *)enumName;

+ (id<JavaUtilList>)getEnumListWithIOSClass:(IOSClass *)enumClass;

+ (id<JavaUtilMap>)getEnumMapWithIOSClass:(IOSClass *)enumClass;

+ (jboolean)isValidEnumWithIOSClass:(IOSClass *)enumClass
                       withNSString:(NSString *)enumName;

+ (JavaUtilEnumSet *)processBitVectorWithIOSClass:(IOSClass *)enumClass
                                         withLong:(jlong)value;

+ (JavaUtilEnumSet *)processBitVectorsWithIOSClass:(IOSClass *)enumClass
                                     withLongArray:(IOSLongArray *)values;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsLang3EnumUtils)

FOUNDATION_EXPORT void OrgApacheCommonsLang3EnumUtils_init(OrgApacheCommonsLang3EnumUtils *self);

FOUNDATION_EXPORT OrgApacheCommonsLang3EnumUtils *new_OrgApacheCommonsLang3EnumUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheCommonsLang3EnumUtils *create_OrgApacheCommonsLang3EnumUtils_init();

FOUNDATION_EXPORT id<JavaUtilMap> OrgApacheCommonsLang3EnumUtils_getEnumMapWithIOSClass_(IOSClass *enumClass);

FOUNDATION_EXPORT id<JavaUtilList> OrgApacheCommonsLang3EnumUtils_getEnumListWithIOSClass_(IOSClass *enumClass);

FOUNDATION_EXPORT jboolean OrgApacheCommonsLang3EnumUtils_isValidEnumWithIOSClass_withNSString_(IOSClass *enumClass, NSString *enumName);

FOUNDATION_EXPORT JavaLangEnum *OrgApacheCommonsLang3EnumUtils_getEnumWithIOSClass_withNSString_(IOSClass *enumClass, NSString *enumName);

FOUNDATION_EXPORT jlong OrgApacheCommonsLang3EnumUtils_generateBitVectorWithIOSClass_withJavaLangIterable_(IOSClass *enumClass, id<JavaLangIterable> values);

FOUNDATION_EXPORT IOSLongArray *OrgApacheCommonsLang3EnumUtils_generateBitVectorsWithIOSClass_withJavaLangIterable_(IOSClass *enumClass, id<JavaLangIterable> values);

FOUNDATION_EXPORT jlong OrgApacheCommonsLang3EnumUtils_generateBitVectorWithIOSClass_withJavaLangEnumArray_(IOSClass *enumClass, IOSObjectArray *values);

FOUNDATION_EXPORT IOSLongArray *OrgApacheCommonsLang3EnumUtils_generateBitVectorsWithIOSClass_withJavaLangEnumArray_(IOSClass *enumClass, IOSObjectArray *values);

FOUNDATION_EXPORT JavaUtilEnumSet *OrgApacheCommonsLang3EnumUtils_processBitVectorWithIOSClass_withLong_(IOSClass *enumClass, jlong value);

FOUNDATION_EXPORT JavaUtilEnumSet *OrgApacheCommonsLang3EnumUtils_processBitVectorsWithIOSClass_withLongArray_(IOSClass *enumClass, IOSLongArray *values);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsLang3EnumUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsLang3EnumUtils")
