//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:offline-index-1.0.jar!com/flatirons/ppmob/common/ICommonService.java
//

#include "J2ObjC_source.h"
#include "com/flatirons/ppmob/common/ICommonService.h"

@interface ComFlatironsPpmobCommonICommonService : NSObject

@end

@implementation ComFlatironsPpmobCommonICommonService

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _ComFlatironsPpmobCommonICommonService = { "ICommonService", "com.flatirons.ppmob.common", NULL, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, -1, -1 };
  return &_ComFlatironsPpmobCommonICommonService;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFlatironsPpmobCommonICommonService)
