//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:commons-codec-1.10-sources.jar!org/apache/commons/codec/language/bm/BeiderMorseEncoder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder")
#ifdef RESTRICT_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder
#define INCLUDE_ALL_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder 0
#else
#define INCLUDE_ALL_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder 1
#endif
#undef RESTRICT_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder

#if !defined (OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder_) && (INCLUDE_ALL_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder || defined(INCLUDE_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder))
#define OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder_

#define RESTRICT_OrgApacheCommonsCodecStringEncoder 1
#define INCLUDE_OrgApacheCommonsCodecStringEncoder 1
#include "org/apache/commons/codec/StringEncoder.h"

@class OrgApacheCommonsCodecLanguageBmNameType;
@class OrgApacheCommonsCodecLanguageBmRuleType;

@interface OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder : NSObject < OrgApacheCommonsCodecStringEncoder >

#pragma mark Public

- (instancetype)init;

- (id)encodeWithId:(id)source;

- (NSString *)encodeWithNSString:(NSString *)source;

- (OrgApacheCommonsCodecLanguageBmNameType *)getNameType;

- (OrgApacheCommonsCodecLanguageBmRuleType *)getRuleType;

- (jboolean)isConcat;

- (void)setConcatWithBoolean:(jboolean)concat;

- (void)setMaxPhonemesWithInt:(jint)maxPhonemes;

- (void)setNameTypeWithOrgApacheCommonsCodecLanguageBmNameType:(OrgApacheCommonsCodecLanguageBmNameType *)nameType;

- (void)setRuleTypeWithOrgApacheCommonsCodecLanguageBmRuleType:(OrgApacheCommonsCodecLanguageBmRuleType *)ruleType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder)

FOUNDATION_EXPORT void OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder_init(OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder *self);

FOUNDATION_EXPORT OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder *new_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder *create_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheCommonsCodecLanguageBmBeiderMorseEncoder")
